# yaml-language-server: $schema=none
kind: recipe
name: mayaflux-edge
description: "Build recipe for MayaFlux development builds"
version: "{debversion}~git{gitdate}~{gitcommit}"

fetch:
  - type: git
    url: "https://github.com/MayaFlux/MayaFlux.git"
    branch: "main"

fetch-debian:
  - type: git
    url: "https://github.com/MayaFlux/launchpad-MayaFlux.git"
    branch: "main"
    subdirectory: "ubuntu"

build:
  architecture: any
  series:
    - questing
  pocket: universe
  ppa: mayaflux/mayaflux-edge
  distribution: questing/main
